apiVersion: v1
kind: Namespace
metadata: 
  name: data-grid

---

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: data-grid-operator-group
  namespace: data-grid
spec:
  targetNamespaces:
    - data-grid
  upgradeStrategy: Default

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: datagrid-subscription
  namespace: data-grid
spec:
  channel: 8.4.x
  installPlanApproval: Automatic
  name: datagrid
  source: redhat-operators
  sourceNamespace: openshift-marketplace