apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-cluster-certificate
  namespace: openshift-config
spec:
  commonName: "*.apps.ocp.snimmo.com"
  dnsNames:
    - "*.apps.ocp.snimmo.com"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-staging-cluster-issuer
  secretName: letsencrypt-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: openshift-ingress-operator,openshift-ingress
      reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
    
