apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-cluster-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: nimmo@redhat.com
    privateKeySecretRef:
      name: letsencrypt-staging-cluster-issuer
    solvers:
    - dns01:
        cloudflare:
          email: nimmo@redhat.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token